/**
 * Synthetic fixtures, hand-authored. The live corpus carries Sched-authored
 * prose and is gitignored (tests/fixtures/live/, regenerated by `npm run
 * fixtures`), so everything committed here is invented: fake UIDs, fake rooms,
 * descriptions written for this file.
 *
 * The shapes are copied faithfully from the live feed — folded DESCRIPTION
 * lines, `\,` escapes, the `U: UPDATED` category prefix, the list view's
 * `type/<Track>/<Subtype>` anchors — because those shapes are the thing under
 * test.
 */

export const UID_PANEL = '1111111111111111111111111111aaaa'
export const UID_GAME = '2222222222222222222222222222bbbb'
export const UID_LATE = '3333333333333333333333333333cccc'
export const UID_FARFUTURE = '4444444444444444444444444444dddd'

/**
 * Four events spanning the cases the pipeline has to get right:
 * a normal panel, a long ambient games block, one that crosses midnight, and
 * one with a DTEND two years out (the live "Dice Throne" shape).
 */
export const ICS = [
  'BEGIN:VCALENDAR',
  'VERSION:2.0',
  'PRODID:-//synthetic//test//EN',
  'BEGIN:VEVENT',
  `UID:${UID_PANEL}`,
  'SUMMARY:Drawing Robots for Fun',
  'DTSTART:20260723T170000Z',
  'DTEND:20260723T180000Z',
  'CATEGORIES:U: UPDATED,1: PROGRAMS',
  'LOCATION:Room 5 (Upper Level)\\, 111 Harbor Dr\\, San Diego\\, CA 92101\\, USA',
  'DESCRIPTION:A folded description that continues onto a',
  '  second physical line\\; with a semicolon.',
  'URL:https://example.test/event/AAAAA',
  'END:VEVENT',
  'BEGIN:VEVENT',
  `UID:${UID_GAME}`,
  'SUMMARY:Open Table Gaming',
  'DTSTART:20260723T170000Z',
  'DTEND:20260724T060000Z',
  'CATEGORIES:6: GAMES',
  'LOCATION:Hall H',
  'DESCRIPTION:Drop in any time.',
  'END:VEVENT',
  'BEGIN:VEVENT',
  `UID:${UID_LATE}`,
  'SUMMARY:Midnight Movie Marathon',
  'DTSTART:20260724T043000Z',
  'DTEND:20260724T073000Z',
  'CATEGORIES:N: NEW,8: FILMS',
  'LOCATION:Screening Room 2',
  'DESCRIPTION:Starts late on the 23rd\\, ends after midnight.',
  'END:VEVENT',
  'BEGIN:VEVENT',
  `UID:${UID_FARFUTURE}`,
  'SUMMARY:Endless Dice Game',
  'DTSTART:20260726T170000Z',
  'DTEND:20280727T010000Z',
  'CATEGORIES:6: GAMES',
  'LOCATION:Gaming Annex',
  'DESCRIPTION:Sched typo: the end date is two years out.',
  'END:VEVENT',
  'END:VCALENDAR',
].join('\r\n')

/** The `/list/descriptions` shape: an anchor carrying shortId + UID, then a
 *  `sched-event-type` block whose links carry the subtype vocabulary. */
export const LIST_HTML = `
<div class="sched-container">
  <a href="event/AAAAA/drawing-robots-for-fun" id="${UID_PANEL}" class="name">Drawing Robots for Fun</a>
  <div class="sched-event-type">
    <a href="/type/1%3A+PROGRAMS">1: PROGRAMS</a>
    <a href="/type/1%3A+PROGRAMS/Comics">Comics</a>
    <a href="/type/1%3A+PROGRAMS/Sci-Fi+%26+Fantasy">Sci-Fi &amp; Fantasy</a>
  </div>
  <a href="event/BBBBB/open-table-gaming" id="${UID_GAME}" class="name">Open Table Gaming</a>
  <div class="sched-event-type">
    <a href="/type/6%3A+GAMES">6: GAMES</a>
    <a href="/type/6%3A+GAMES/Tabletop+Games">Tabletop Games</a>
  </div>
  <a href="event/CCCCC/midnight-movie-marathon" id="${UID_LATE}" class="name">Midnight Movie Marathon</a>
  <div class="sched-event-type">
    <a href="/type/8%3A+FILMS">8: FILMS</a>
    <a href="/type/8%3A+FILMS/Screenings">Screenings</a>
  </div>
  <a href="event/DDDDD/endless-dice-game" id="${UID_FARFUTURE}" class="name">Endless Dice Game</a>
  <div class="sched-event-type">
    <a href="/type/6%3A+GAMES">6: GAMES</a>
    <a href="/type/6%3A+GAMES/Tabletop+Games">Tabletop Games</a>
  </div>
</div>
`

/** The drift-guard trigger: valid HTML, no event anchors at all. */
export const LIST_HTML_EMPTY = '<div class="sched-container"><p>Nothing here.</p></div>'
